spring:
  profiles:
    active: @env@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      indent_output: false